/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/system-controls`; params?: Router.UnknownInputParams; } | { pathname: `/running-apps`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/components/ActionButton`; params?: Router.UnknownInputParams; } | { pathname: `/components/AppListItem`; params?: Router.UnknownInputParams; } | { pathname: `/components/ErrorDisplay`; params?: Router.UnknownInputParams; } | { pathname: `/components/LoadingSpinner`; params?: Router.UnknownInputParams; } | { pathname: `/components/NetworkInfoCard`; params?: Router.UnknownInputParams; } | { pathname: `/components/Section`; params?: Router.UnknownInputParams; } | { pathname: `/components/SystemInfoCard`; params?: Router.UnknownInputParams; } | { pathname: `/constants/apiConfig`; params?: Router.UnknownInputParams; } | { pathname: `/hooks/useSystemData`; params?: Router.UnknownInputParams; } | { pathname: `/services/api`; params?: Router.UnknownInputParams; } | { pathname: `/types/api`; params?: Router.UnknownInputParams; } | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/system-controls`; params?: Router.UnknownOutputParams; } | { pathname: `/running-apps`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `/components/ActionButton`; params?: Router.UnknownOutputParams; } | { pathname: `/components/AppListItem`; params?: Router.UnknownOutputParams; } | { pathname: `/components/ErrorDisplay`; params?: Router.UnknownOutputParams; } | { pathname: `/components/LoadingSpinner`; params?: Router.UnknownOutputParams; } | { pathname: `/components/NetworkInfoCard`; params?: Router.UnknownOutputParams; } | { pathname: `/components/Section`; params?: Router.UnknownOutputParams; } | { pathname: `/components/SystemInfoCard`; params?: Router.UnknownOutputParams; } | { pathname: `/constants/apiConfig`; params?: Router.UnknownOutputParams; } | { pathname: `/hooks/useSystemData`; params?: Router.UnknownOutputParams; } | { pathname: `/services/api`; params?: Router.UnknownOutputParams; } | { pathname: `/types/api`; params?: Router.UnknownOutputParams; } | { pathname: `/+not-found`, params: Router.UnknownOutputParams & {  } };
      href: Router.RelativePathString | Router.ExternalPathString | `/${`?${string}` | `#${string}` | ''}` | `/system-controls${`?${string}` | `#${string}` | ''}` | `/running-apps${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `/components/ActionButton${`?${string}` | `#${string}` | ''}` | `/components/AppListItem${`?${string}` | `#${string}` | ''}` | `/components/ErrorDisplay${`?${string}` | `#${string}` | ''}` | `/components/LoadingSpinner${`?${string}` | `#${string}` | ''}` | `/components/NetworkInfoCard${`?${string}` | `#${string}` | ''}` | `/components/Section${`?${string}` | `#${string}` | ''}` | `/components/SystemInfoCard${`?${string}` | `#${string}` | ''}` | `/constants/apiConfig${`?${string}` | `#${string}` | ''}` | `/hooks/useSystemData${`?${string}` | `#${string}` | ''}` | `/services/api${`?${string}` | `#${string}` | ''}` | `/types/api${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/system-controls`; params?: Router.UnknownInputParams; } | { pathname: `/running-apps`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/components/ActionButton`; params?: Router.UnknownInputParams; } | { pathname: `/components/AppListItem`; params?: Router.UnknownInputParams; } | { pathname: `/components/ErrorDisplay`; params?: Router.UnknownInputParams; } | { pathname: `/components/LoadingSpinner`; params?: Router.UnknownInputParams; } | { pathname: `/components/NetworkInfoCard`; params?: Router.UnknownInputParams; } | { pathname: `/components/Section`; params?: Router.UnknownInputParams; } | { pathname: `/components/SystemInfoCard`; params?: Router.UnknownInputParams; } | { pathname: `/constants/apiConfig`; params?: Router.UnknownInputParams; } | { pathname: `/hooks/useSystemData`; params?: Router.UnknownInputParams; } | { pathname: `/services/api`; params?: Router.UnknownInputParams; } | { pathname: `/types/api`; params?: Router.UnknownInputParams; } | `/+not-found` | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } };
    }
  }
}
